language: java
jdk:
- openjdk8
branches:
  only:
  - master
script:
- "./gradlew build shadowJar -x test"
before_deploy: cd orders
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username:
    secure: NWOQPp7wGfF8EHn7Y7C+LL5f8WpubZL2odvdP5UBXRqvHExoG/YfTibF/+vpVVHb6DVp57TqtYFfXIWQwjXHiLdDeLjUqdaUIjpykJzWCmIngM4BxUXqMCSY+Vig2eOt3yOYXhUTZ/lIyiFqHwzLFM9UCh6f8QRju0FmGBdXYxTBBLxd2IfdpzhC8txjkVEQ9dqXqoa3MM3OGMFYXxXmkwRmdrozejE7TWkaEdmJY2YY9eV4eXABEf2dRsRu7s1qoUaVgxLand34XcWZnEWXXPLRe1m6da/vjY87LXagmg3yfi2GgNJWh+HgmBzWn4qSiCKdIxZV76rJ73fbp5hBD99AXSu6R7SgqUGzKOzPKHoECQMEmgKRhh15TDv+4hg8wNXjbJI5y6vn090NeggapsyT1+KS6sCIIHNIVhYN/BDoC2zANm9rrb+iN0DIoyq5ZLkuZz/gimMoFNhonrMm+4kSXXNZ1TiRlTr0cPhIGiNDN49L969mioXAzuvLdRxvQpssy/k5btPy4liL1jxtMqofx5LPi5mqhlT32Y8mtkxEuNyy4CfgYZvPTcn8Mpfd0SG8U5xBFsExJrsUPBm6ubIwQ1ZC/N9db/XvNtRPIOjMbS5/V6G9njDj7y2QpN2vszy5KlQGzr0z2LhDTSUOiVUrsp51YO6kB75ABm7kW4I=
  password:
    secure: v5RXi8ZX6BZdYLROCY0DXjP3mXV84PoT74Gw6kJTzuKDBy0sb5u72mADd4iwVkVQO+dXMEq+10FhzHv9F04RVdZgMUvziyurCR91191zmen1eEDSm7w+BfHfLSDvlhcweAbKBNl5AkTK7VKmCuWlHbPIC7ByW+PS9uVkiMLGt62V+vWwngASkKgIYtV4fpImh2hmwRRvikVpRErN0H2fNjJ7JB2z7Z+8xT5HKeMAsGrHkYL8iN89v9IkBlGO7Bg8aTjENumtdt8EgFqZAhoNpwX/y805DTlIeKkrJHXMXw35mvtTzpXuHOt0KBlzGYcUd6yeV2LLn4GGQs2/I5KTN7BpzF0TPUqYGo+3mHyFYxamGWuMwa2RhHtTvT6rwB7V83ZA2cBjBZtQJg8JhulEQ9lpIrpispEKI+OalSlf5inQvh6uDnqt8v4A/410xfkqiwR0zHa9g+oDgzR7bqCGDvl/ymicgc0Hy7r5K+XAnpEe58XeEvP5IpeMniwziVHHcRxBglKiGmkoETLUpk2db1oWVzs8cnH4xOETLsicOZ6FSpJ7dYQTz4V4XHceyVoN7W/Be99o+YUUBjydSzpxgtIur39dVB7TDgylDHNRf5oA4cxP/AmIpi6ZnDX5DJgW/9o4cI83wepWw6mw8BJ5MWZv9TJ8PAnoVeTguuvmolI=
  organization:
    secure: Twz/Bfamelx9jd0C/uxOWtR6N5qrpQqRY8NBEz0mSh2FWUbtKwoazAvK04bDl0ZpMZlIndH/V/N+tC8A4wIZltKmv9NS0LGfaUVAAs5LZLyF5mnvXkWLoK697hndP15lqnbet7fDfgPYodPdtyt+498SJ19YGNo59YdkqN36PxeH+/i9+oqlehOEkHyOmlixU+QbvcsCaIEoYOJvFU8O3575rsJRB8oAqwji9b4NpvswK4VnicnEfC42X7YxDI4+AKYANimV541RFvJooGLpEw+xtYPAthVCCO6AtEuLoTpD34wehQqEZco5tHOY6d9uS7ijtxVz6vj5TCA5Jv23LpmCGxzBrKXFb828ZEP4uUqkNh/1lNTxXblhjMajEU6mGb+/b9zISqNknUE1QOzYqMK+qpwxjlN9qMRY1Eh4GjAgLl1u8t9Q0lRV2Kmfy9bOSL1LYQS4O7m0u0ej4yt9YEwFXthM3DUZbOstD7bN0ggwB7tBPadyoEuW/YCPrkWDZy5f6el0Prw04OOk69q/NqisKfTIl6c1wQ9EFwJkEwJTycE687Sq57mo8TGqPhlGrYLKzjnd2BC3Udv+rd7+4+mjlwc+N3ubHxcsOJ2304szeF4LOxVNHa5xoy0MdfbaDCBjWf6z/NiQxye7IUOnx4Fh3KPzZBNWnWUL+UMbw+g=
  space: development
  on:
    branch: master
notifications:
  email:
    on_failure: change
    on_success: change
