language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
script:
- "./gradlew build shadowJar -x test"
before_deploy: cd orders
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  space: development
  on:
    branch: master
notifications:
  email:
    on_failure: change
    on_success: change
env:
  global:
  - secure: mUg2Vcl80FVnPdtt5hom7UyIvUV1piaresNxbbS0xxzDRytlpkbyzShg2HIjqne+i1A3rXe8C0w5C5hB5m0Q9JAFbA95AXCrKiPa8jZTGbcLySjHjG07LhLb++JvjHn5tl8HsHhuthts5nwqAaigVsLBc4J3aiXPWwpsNPjPKyL6yzUdkBrVBbHRNJAf53WMGs0VcH8mnhIQ6XDWRewlUjKm8naBaqc8RUvXZwBRQlaCmNBQ0hYIqi45wgOmwL7jYE0GlrDx3sELQvtY++4MbEpvWO1z2qxGwQ3yznvSfWUGA37Frxggt0Il9a2SJnLExDVXI3QGnHu/HHBdiZbmJEJloaDjrpOpdK9VktOd3RdhvT/3W6kDRw4RFA3wDgBqQoi6xeS6QEd9P5YgoZNUvnGfJweHU0Mkst+SKTkeNzVc4fiH8oVAc6Xq4dTkEXHX5/1VNVGNxxYjc4b60bR08kJ71uWjmv3mVGcPn6sCC/15ZUU3s709DPM66XAtKoCOjihRDF+ilptmDqqdwGneRk3jFSJBSgZPwfi3UrlidiShmGGqwq+FrqCi+OqyhejfP+w1ij1ZjYWr8MJyjoNyFZbOlIQhqgPzHQfFoOlFiV72ewyhmj9+oXV2ohRqnpENcgtLV1xBYgRNE2e0euFUEmQdKORLUOgGP0hrI6fSGeA=
  - secure: hU3Dgee1FsICxZalg2biXLt1wLdy8rFufjB0n6cK/O8ZUlujUU5NEwCNbUJgCp1nb9bgX2u9wPVVmA/8P0J8uSypE90Uajij9n+IrwccS87ELKK4W85g7/09a92DAwZH0fqg2NT6GTqES4PMMn9Hz6GASuSfZtyk0qkLFq84iVzZNtuP4ODQYdeywRMNNatVOkI+nDTgis8WztqXpJmrOUqlwhY6j5oGC9NG24LPCjnvMVBPyGCByA/zGzdPNHHnuCJu6flxbB9dO5Jy0adXJNJgKu4gpIT02uN3UZaREDTajF9DW36z/yvJAzPsPxteTsdN7zUT12yRUF5OFo7MXW78DUoa0dlHxwSo84yKQxije1sVunCcIynNvJaM1Q9dsMOBgm//tCtgt+NhPS66g2XkdON/8xz/mjZ2ZL3vKY7vMRWTfSQjaEjS+5I4fnzIbAL5WZZSvk0rPGNGkfEWnr5a4Mw5ybaPvqq1lVxgnV+jTiYlAIYw3NaaOHWW4+1Xe4j9u9WO3kHTlbS+WEt54ZuyeC6bKq5xRpw6E8uEaDKcqJpcCVmApLNzN9izd3gFr14rhdL4ecOKivbFLtQAsvNnmTnHeSF5qiWczgP/I7v4Uj9baTBizd3WtLBWylqXCAD+gJZREPH8I+IcXFd1tCaFKh+0C58QWnpsCnDMD98=
  - secure: odq8awV2BueG18NXXRifdXD9yiflAN4r3dg8o8umMizXQrBQFWm7SN/gUmYlynVKxjkJRA3gL+kBDbU2hNtj6ejEUSjmEHYgUfJv83uPsx9beZZ8qoykv9Wd8gEwdp4eL1rVhhewdiWnDLQv1MXjLycUF+tS5HQgVwhc5gQHAGP7rVKZFnHChg45ZuNNraK8XVJf9MssvnwzV1VEFiWYbBUnCtaiI8SbgduqbE6K78ggPp+aKjQ7nYlZqIZPda2gtDWSuujatp31cs04u2CQ5W/8OCxBzuzgNlMMtyIFa1KXjkcy/He+2ykZAQL6gm14tYzjC2cn8XIopF6iF/gV3LumhFO6ACuo0uuCgC1DD7KlAd+AB3zRNKmZ14pBrcqiEETCOCfDXHcc88HZMACcsu1mRagNbSTEGC6V5RRVE+sPAO0QmimRmcN48bbuyINXMs43dxdnfoirtHWcfumxzxRG7zr1PPqOYmFqipbTrITnUJXeoAuj/VjtB96RaGa/PL8OOdWijFO3NsBiQWwQnzMbrdBLscnswqlpS7KozAPTG3VBVZZZptg10CheqJLX9SKSSfDH9P54WFnoMeEBbRXSQT5H0Iw1ZAEZYbO+zM5VPjPqavYuwqNwW3ObMb/yltr3nUDyNiGa1Cv4J1YCt0zAvAtnturVcJtnJ9l2sos=
